### PR TITLE
Update to 3.0.3 of jquery.cycle

### PR DESCRIPTION
**Pull request by jbickar**
It appears we are using version 3.0.3 on Sites.

### CODE REVIEW

**Comment by sherakama** [comment]
since when? All of our make files are pointed to v2.99?

**Comment by jbickar** [comment]
Dunno. That's what's on disk. I will look through the git logs.

**Comment by jbickar** [comment]
Since May 6, 2015:

```
commit 416035ae69ac27902d6730085caccef6d3dd8071
Author: John Bickar <jbickar@stanford.edu>
Date:   Wed May 6 11:08:15 2015 -0700

    Major re-architecture to use drush make to build the repo
    
    Moved modules into subdirectories within sites/all/modules:
      sites/all/modules/contrib
      sites/all/modules/stanford
    Updated stanford profile to 7.x-2.x
    Added json2 library (required by views_slideshow)
    Added spyc library (required by services)
    Updated sites/all/modules/README.txt and sites/default/default.settings.php
      to match what comes with current version of Drupal (7.35)
```

`/blame @jbickar`

**Comment by sherakama** [comment]
Well... if it has been that was since may 6 I guess it hasn't broken anything. Not my favorite method of testing but usually pretty effective.

**Comment by jbickar** [comment]
I had a typo; it's actually since May, **2015**.

This is actually my favorite method of testing.

**Comment by sherakama** [comment]
Facepalm

**Comment by jbickar** [comment]
2015 was a good year.

Actually, no it wasn't, but the point stands that almost 3 years of testing should be good enough.

**Pull request merged**
